version: '3.8'

services:
  app:
 # ... other configurations
    user: "1000:1000" # Ganti dengan user ID dan group ID Anda
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aimeos-app
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: aimeos-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

<<<<<<< HEAD
# Service untuk database MySQL
db:
  image: mysql:8.0
  container_name: aimeos-db
  restart: always
  environment:
    - MYSQL_DATABASE=${DB_DATABASE}
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  volumes:
    - dbdata:/var/lib/mysql
=======
  db:
    image: mysql:8.0
    container_name: aimeos-db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
>>>>>>> refs/remotes/origin/main

volumes:
  dbdata:
