name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-porto-470103 # Ganti dengan ID Proyek GCP Anda
  GCE_ZONE: asia-southeast2-a # Ganti dengan zona VM Anda
  GCE_INSTANCE: testing # Ganti dengan nama VM Anda
  GAR_LOCATION: asia-southeast2-a # Lokasi Artifact Registry, sesuaikan jika perlu (e.g., asia-southeast2)
  IMAGE_NAME: aimeos-app # Nama image Docker Anda

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Authentikasi ke Google Cloud menggunakan Service Account Key
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Set up Google Cloud CLI (opsional jika hanya butuh Docker, tapi bagus untuk gcloud compute)
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    # Konfigurasi Docker untuk push ke Artifact Registry
    - name: Configure Docker to push to Artifact Registry
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    # Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .

    # Push Docker Image to Artifact Registry (sebelumnya GCR)
    - name: Push Docker Image to Artifact Registry
      run: docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

    # Deploy ke GCE
    - name: Deploy to GCE
      run: |
        gcloud compute ssh ${{ env.GCE_INSTANCE }} --zone ${{ env.GCE_ZONE }} --command "
          sudo docker pull ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest && \
          cd /var/www/html && \
          sudo docker-compose down && \
          sudo docker-compose up -d
        "
